---
title: 错误页面
sidebar_label: 错误页面
---

## 404 页面 {#404-page}

404 页面可能经常被访问，因此 Blitz 默认情况下会提供静态 404 页面，而无需添
加任何其他文件。

### 自定义 404 页面 {#customizing-the-404-page}

要创建自定义 404 页面，你可以创建一个 `app/pages/404.js` 文件。该文件在编
译时静态生成。

```jsx
// app/pages/404.js
export default function Custom404() {
  return <h1>404 - Page Not Found</h1>
}
```

## 500 页面 {#500-page}

默认情况下，Blitz 提供了一个 500 错误页面，该页面与默认 404 页面的样式相匹
配。此页面不是静态优化的页面，因为它允许展示服务端错误。这就是为什么将 404
和 500（其他错误）分开的原因。

### 自定义错误页面 {#customizing-the-error-page}

`Error` 组件可同时在客户端和服务端处理 500 错误。如果你想要覆盖它，请定义
文件 `app/pages/_error.js` 并添加如下代码：

```jsx
function Error({statusCode}) {
  return (
    <p>
      {statusCode
        ? `An error ${statusCode} occurred on server`
        : "An error occurred on client"}
    </p>
  )
}

Error.getInitialProps = ({res, err}) => {
  const statusCode = res ? res.statusCode : err ? err.statusCode : 404
  return {statusCode}
}

export default Error
```

> `app/pages/_error.js` 仅在生产中使用。在开发中，你会在调用堆栈中遇到错误
> ，以便了解错误的出处。

## 自定义错误边界回退组件 {#custom-error-boundary-component}

`app/pages/_app.tsx` 默认配置一个错误边界，该边界捕获客户端渲染期间发生的
错误。这也将捕获意外情况下的 `useQuery` 或 `useMutation` 错误。

本质上，默认配置为：

```tsx
export default function App({Component, pageProps}: AppProps) {
  return (
    <ErrorBoundary FallbackComponent={RootErrorFallback} {...etc}>
      {getLayout(<Component {...pageProps} />)}
    </ErrorBoundary>
  )
}
```

当渲染内发生错误或暂停 mutation 或 query 时，将渲染 `RootErrorFallback`。
默认情况下：

```tsx
function RootErrorFallback({
  error,
  resetErrorBoundary,
}: ErrorFallbackProps) {
  if (error instanceof AuthenticationError) {
    return <LoginForm onSuccess={resetErrorBoundary} />
  } else if (error instanceof AuthorizationError) {
    return (
      <ErrorComponent
        statusCode={error.statusCode}
        title="Sorry, you are not authorized to access this"
      />
    )
  } else {
    return (
      <ErrorComponent
        statusCode={error.statusCode || 400}
        title={error.message || error.name}
      />
    )
  }
}
```

### 身份验证错误组件（401） {#custom-authentication-error-component}

如果你的 query、mutation 或渲染函数在用户身份未验证通过时
`throw new AuthenticationError()`，则可以再错误回调中检测到该错误。

```tsx
function RootErrorFallback({
  error,
  resetErrorBoundary,
}: ErrorFallbackProps) {
  if (error instanceof AuthenticationError) {
    return <MyCustomError error={error} onRetry={resetErrorBoundary} />
  }
  return (
    <ErrorComponent
      statusCode={error.statusCode || 400}
      title={error.message || error.name}
    />
  )
}
```

### 鉴权错误组件（403） {#custom-authorization-error-component}

当用户通过身份验证但无权做某事时，你的 query、mutation 或渲染函数可能会调
用 `throw new AuthorizationError()`。错误回调可能会这样处理：

```tsx
function RootErrorFallback({
  error,
  resetErrorBoundary,
}: ErrorFallbackProps) {
  if (error instanceof AuthorizationError) {
    return <MyCustomError error={error} onRetry={resetErrorBoundary} />
  }
  return (
    <ErrorComponent
      statusCode={error.statusCode || 400}
      title={error.message || error.name}
    />
  )
}
```

## 重用内置错误页面 {#reusing-the-built-in-error-page}

你可以通过导入 `ErrorComponent` 渲染内置错误页面。

它接收两个 props：

- `statusCode` - 一个用来显示错误代码的数字
- `title` - 一个用来显示错误代码的字符串

```jsx
import {ErrorComponent} from "blitz"

export default function Page() {
  return <ErrorComponent statusCode={404} />
}
```

```jsx
import {ErrorComponent} from "blitz"

export default function Page() {
  return <ErrorComponent statusCode={401} title="Unauthorized" />
}
```
