---
title: 错误处理
sidebar_label: 错误处理
---

## 内置错误 {#built-in-errors}

Blitz 带有许多有用的错误，你可以在整个应用程序中使用。

- `AuthenticationError`
  - `name`: "AuthenticationError"
  - `statusCode`: 401
  - 默认 `message`: "You must be logged in to access this"
- `CSRFTokenMismatchError`
  - `name`: "CSRFTokenMismatchError"
  - `statusCode`: 401
  - 默认 `message`: "You must be logged in to access this"
- `AuthorizationError`
  - `name`: "AuthorizationError"
  - `statusCode`: 403
  - 默认 `message`: "You are not authorized to access this"
- `NotFoundError`
  - `name`: "NotFoundError"
  - `statusCode`: 404
  - 默认 `message`: "This could not be found"

为了使用，从 `blitz` 中导入并像任何 JavaScript Error 对象一样使用。如果你
好奇，你可以
[查看这些代码的源代码](https://github.com/blitz-js/blitz/blob/canary/packages/core/src/errors.ts)。

```ts
import { AuthenticationError } from "blitz"
try {
  throw new AuthenticationError()
} catch (error) {
  if (error.name === "AuthenticationError") {
    // Handle this error appropriately, like show a login screen
    console.log(error.statusCode)
    console.log(error.message)
  }
}
```

你可以从应用中的任何位置跑出这些错误或其它任何错误，无论是在服务器上还是在
客户端上。

## 在客户端上捕获和处理错误 {#catching-and-handling-errors-on-the-client}

默认情况下，新的 Blitz 应用带有
[`react-error-boundary`](https://github.com/bvaughn/react-error-boundary)，
在应用的 `app/pages/_app.tsx` 中安装了顶层的 `ErrorBoundary` and
`FallbackComponent`。

看起来像这样：

```tsx
// app/pages/_app.tsx
import { AppProps, ErrorComponent } from "blitz"
import { ErrorBoundary } from "react-error-boundary"
import { queryCache } from "react-query"
import LoginForm from "app/auth/components/LoginForm"
export default function App({ Component, pageProps }: AppProps) {
  return (
    <ErrorBoundary
      FallbackComponent={RootErrorFallback}
      onReset={() => {
        // This ensures the Blitz useQuery hooks will automatically refetch
        // data any time you reset the error boundary
        queryCache.resetErrorBoundaries()
      }}
    >
      <Component {...pageProps} />
    </ErrorBoundary>
  )
}
function RootErrorFallback({ error, resetErrorBoundary }) {
  if (error.name === "AuthenticationError") {
    return <LoginForm onSuccess={resetErrorBoundary} />
  } else if (error.name === "AuthorizationError") {
    return (
      <ErrorComponent
        statusCode={error.statusCode}
        title="Sorry, you are not authorized to access this"
      />
    )
  } else {
    return (
      <ErrorComponent
        statusCode={error.statusCode || 400}
        title={error.message || error.name}
      />
    )
  }
}
```

这意味着所有错误至少将在根级别被捕获。但是，你还可以在应用中的任何其它地方
添加 `<ErrorBoundary>`，以进行更局部的错误处理。如果错误在应用程序树中的某
个位置的某个地方被 `<ErrorBoundary>` 捕获，除非重新抛出该错误，否则它将不
会到达根 `<ErrorBoundary>`。

### 在客户端上处理服务器错误 {#handling-server-errors-on-the-client}

Blitz 的一个真正令人敬畏的功能是，你可以引发 Blitz query 或 mutation 中的
任何错误，然后在前端中使用 ErrorBoundary 来捕获并处理它。

例如，使用上面的 `app.tsx`，你可以在 Blitz query 中抛出
`AuthenticationError`，然后登陆页面将自动显示在客户端中，因为如果
`error.name === 'AuthenticationError'`，根 ErrorBoundary 将会渲染
`<LoginForm>`。

### 自定义错误 {#custom-errors}

对于 Blitz 提供的错误类型以外的错误，建议创建自定义 Error 类。然后，你可以
添加自定义数据属性，以帮助你处理错误。

这是有关如何创建自定义错误的示例。这是一个 JavaScript 类，因此你可以根据需
要发挥创造力。

```ts
import SuperJson from "superjson"
export class UsernameTakenError extends Error {
  name = "UsernameTakenError"
  constructor({ suggestedUserName }) {
    super()
    this.suggestedUserName = suggestedUserName
  }
}
// 使用 SuperJSON 序列化器注册，以便在客户端上对齐复用
SuperJson.registerClass(UsernameTakenError)
SuperJson.allowErrorProps("suggestedUserName")
throw new UsernameTakenError({ suggestedUserName: "second_best" })
```

请注意，你**必须向上面那也使用 SuperJSON 注册**，以便 `instanceof` 可以在
客户端上运行。而且，你还必须告诉 SuperJSON 你要序列化的任何特殊错误属性。
出于安全考虑，默认情况下你将忽略自定义错误属性。

接下来在客户端上，你可以使用上述的 `FallbackComponent`，也可以像这样处理表
单提交处理程序的错误‘：

```tsx
<Form
  onSubmit={async (values) => {
    try {
      await setUsername(values.username)
    } catch (error) {
      if (error instanceof UsernameTakenError) {
        setSuggestedUsername(error.suggestedUserName)
      }
    }
  }}
/>
```

## 错误页面 {#error-pages}

查看[错误页面文档](./error-pages)来了解关于自定义错误页面和错误处理组件的
信息。
